services:
  # 数据库
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=Turcarai2025
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=Turcarai2025
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle_network

  # moodle系统
  moodle:
    image: docker.io/bitnami/moodle:5.0
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Turcarai2025
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=Turcarai2025
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - PHP_DEFAULT_MEMORY_LIMIT=4096M
    volumes:
      - './php.ini:/opt/bitnami/php/etc/php.ini'
      - './moodle:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - moodle_network

  # web接口服务
  newmoodle_api:
    build:
      context: ./backend
      dockerfile: Dockerfile_api
    environment:
      - DB_USER=root
      - DB_PASSWORD=Turcarai2025
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_NAME=tur
    ports:
      - "8001:8000"
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - moodle_network

  # 对话socket.io服务
  newmoodle_ws:
    build:
      context: ./backend
      dockerfile: Dockerfile_ws
    environment:
      - DB_USER=root
      - DB_PASSWORD=Turcarai2025
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_NAME=tur
      - LLM_API_KEY=ollama
      - LLM_BASE_URL=http://192.168.0.5:11434/v1
      - LLM_MODEL_NAME=qwen2.5
    restart: unless-stopped
    ports:
      - "5001:5000"
    depends_on:
      - mariadb
    networks:
      - moodle_network

  # 反向代理
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile05
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/static-files:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      - moodle
      - newmoodle_ws
      - newmoodle_api
    networks:
      - moodle_network

# 网桥
networks:
  moodle_network:
    driver: bridge

# 数据卷
volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
