services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=Turcarai2025
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=Turcarai2025
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - moodle_network

  moodle:
    image: docker.io/bitnami/moodle:5.0
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=Turcarai2025
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=Turcarai2025
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - PHP_DEFAULT_MEMORY_LIMIT=4096M
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './php.ini:/opt/bitnami/php/etc/php.ini'
      - './moodle:/bitnami/moodle'
      # - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - moodle_network

  nginx:
    build:
      context: ./mainpage
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./mainpage/static-files:/usr/share/nginx/html:ro
    restart: unless-stopped
    depends_on:
      - moodle
    networks:
      - moodle_network

  newmoodle_api:
    build:
      context: ./backend
      dockerfile: Dockerfile_api
    environment:
      - DB_USER=root
      - DB_PASSWORD=Turcarai2025
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_NAME=tur
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - moodle
    networks:
      - moodle_network

  newmoodle_ws:
    build:
      context: ./backend
      dockerfile: Dockerfile_ws
    environment:
      - DB_USER=root
      - DB_PASSWORD=Turcarai2025
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_NAME=tur
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - moodle
    networks:
      - moodle_network

networks:
  moodle_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
