version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile_api
    restart: always
    ports:
      - "8000:8000"

  ws:
    build:
      context: ./
      dockerfile: Dockerfile_ws
    restart: always
    ports:
      - "5000:5000"
